export const AUTH_LOGIN_WITH_PHONE = 'auth.AUTH_LOGIN_WITH_PHONE';
export const AUTH_LOGIN_WITH_PHONE_WAITING_FOR_VERIFICATION = 'auth.AUTH_LOGIN_WITH_PHONE_WAITING_FOR_VERIFICATION';
export const AUTH_LOGIN_WITH_PHONE_FAILED = 'auth.AUTH_LOGIN_WITH_PHONE_FAILED';
export const AUTH_LOGIN_WITH_PHONE_VERIFICATION = 'auth.AUTH_LOGIN_WITH_PHONE_VERIFICATION';
export const AUTH_LOGIN_WITH_PHONE_VERIFICATION_SUCCESSFULLY = 'auth.AUTH_LOGIN_WITH_PHONE_VERIFICATION_SUCCESSFULLY';
export const AUTH_LOGIN_WITH_PHONE_VERIFICATION_FAILED = 'auth.AUTH_LOGIN_WITH_PHONE_VERIFICATION_FAILED';